Rewrite internals to be faster and easier to reuse

diff --git a/duck b/duck
--- a/duck
+++ b/duck
@@ -1,40 +1,28 @@
 #!/bin/bash
-set -eu
+set -e
 shopt -s gnu_errfmt
 export LC_ALL=C
-bold=$(tput bold)
-normal=$(tput sgr0)
+bold="$(tput bold)"
+normal="$(tput sgr0)"
 
-INPUT="${1}"
+INPUT="${1:?}"
 
 unset vars
 # associative arrays go brr
 declare -A vars
 
-function replace_var() {
-	true
+function first_word() {
+	local word=($1)
+	echo "${word[0]}"
+	unset word
 }
 
 function errorfmt() {
 	printf '%s\n' "ERROR: $*"
 }
-keys=('#' 'print' 'var' 'unset' 'if' 'exit')
-while IFS= read -r line; do
-	# get first key in line: "foo bar baz" -> "foo"
-	value="${line%% *}"
-	# if line does not contain value and value is not empty (newline), error out
-	if [[ ! " ${keys[*]} " =~ " ${value} " ]] && [[ ! ${value:-null} == null ]]; then
-		errorfmt "(${bold}$line${normal}) is not a valid command"
-		exit 1
-	fi
-	# yoinks comments
-	if [[ "${line}" =~ ^#* ]]; then
-		true
-	fi
-	# print statement
-	if [[ "${line}" =~ ^print ]]; then
-		# if line contains a {}, which means a variable is used
-		if [[ "${line}" == *"{"* ]]; then
+
+function print() {
+	if [[ "${line}" == *"{"* ]]; then
 			# match for both {}
 			if grep --color=none -vE '{.*}' <<< "${line}" 2>/dev/null; then
 				errorfmt "Line does not contain an equal number of brackets"
@@ -49,37 +37,47 @@ while IFS= read -r line; do
 				printf '%s\n' "${looped_line#print }"
 				unset variable_names looped_line
 			fi
-		else
-			# normal print statement
-			printf '%s\n' "${line#print }"
-		fi
+	else
+		# normal print statement
+		printf '%s\n' "${line#print }"
 	fi
+}
 
-	if [[ "${line}" =~ ^var ]]; then
-		key="$(awk '{print $2}' <<< "${line}")"
-		value="$(awk '{print $3}' <<< "${line}")"
-		vars["${key}"]="${value}"
-		unset key value
-	fi
+function var() {
+	key="$1"
+	value="$2"
+	vars["${key}"]="${value}"
+	unset key value tmp_line
+}
 
-	if [[ "${line}" =~ ^unset ]]; then
-		key="${line#unset }"
-		set +u
-		if [[ -z ${vars[$key]} ]]; then
-			errorfmt "$key does not exist"
-			exit 1
-		fi
-		set -u
-		unset -v "vars[$key]"
+function unset_var() {
+	unset -v "vars[$*]"
+}
+keys=('#' 'print' 'var' 'unset')
+while IFS= read -r line; do
+	# get first key in line: "foo bar baz" -> "foo"
+	value="${line%% *}"
+	# if line does not contain value and value is not empty (newline), error out
+	if [[ ! " ${keys[*]} " =~ " ${value} " ]] && [[ ! ${value:-null} == null ]]; then
+		errorfmt "(${bold}$line${normal}) is not a valid command"
+		exit 1
 	fi
-
-	if [[ ${line} =~ ^exit ]]; then
-		exit "${line#exit }"
+	# yoinks comments
+	if [[ "${line}" =~ ^#* ]]; then
+		true
 	fi
-	if [[ ${line} =~ ^if ]]; then
-		if grep --color=none -vE '(.*)' <<< "${line}" 2>/dev/null; then
-			errorfmt "(${bold}$line${normal}) does not contain an equal number of brackets"
-			exit 1
-		fi
+	# print statement
+	if [[ "$(first_word $line)" == "print" ]]; then
+		print "${line#print }"
+	fi
+	if [[ "$(first_word $line)" == "var" ]]; then
+		var "$(awk '{print $2}' <<< "${line}")" "$(awk '{print $3}' <<< "${line}")"
+	fi
+	if [[ "$(first_word $line)" == "unset" ]]; then
+		unset_var "${line#unset }"
 	fi
 done < "${INPUT}"
+
+# cleanup
+unset -f vars
+unset -v INPUT
